# This will serve as a common file to be used with both docker-compose.dev.yml and docker-compose.prod.yml
services:
  node-app:
    image: 22omar/store-api-node-express
    env_file: .env
  
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - node-app